version: '3'

services: 
  db:
    container_name: 'database-node'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp --init-file /docker-entrypoint-initdb.d/init.sql  
    volumes: 
      - .scriptInit/init.sql:/docker-entrypoint-initdb.d/init.sql  
    restart: always
    ports: 
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=desafio-dev-back-1
      - MYSQL_USER=candidato
      - MYSQL_PASSWORD=candidato
      - TZ=America/Sao_Paulo
  app: 
    build: .
    command: yarn start
    restart: always
    ports: 
      - '8081:8081'
    volumes: 
      - .:/usr/app
    depends_on:
      - db 